version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api_root
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "api_root"
      POSTGRES_DB: clientes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local